# Health & Social Person-centric Ontology (HSPO)
site_name: Health & Social Person-centric Ontology (HSPO) User Guide
site_description: Representing a 360-view of a person (or cohort) that spans across multiple domains, from health to social.

#Repository
repo_name: Dublin-Research-Lab/hspo-ontology
repo_url: https://github.ibm.com/Dublin-Research-Lab/hspo-ontology
edit_uri: ''

nav:
- Overview: index.md
- Classes: classes.md
- Building Knowledge Graphs: building-kgs-hspo.md
- Ontology Specification: "ontology-specification/"

#Theme
theme:
    name: material
    features:
      - navigation.top
      - navigation.tracking
      - toc.follow
    palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      icon:
        repo: fontawesome/brands/github-alt
      language: en

markdown_extensions:
  - attr_list
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


#Plugins
plugins:
- search

#Extensions
#markdown_extensions:
#- toc:
#    permalink: true
#- admonition
#- extra
#- attr_list
#- md_in_html

#Customization
extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.ibm.com/Dublin-Research-Lab/hspo-ontology



# Copyright
copyright: Copyright &copy; 2022 <strong>IBM</strong> Research Europe
